version: '2'
services:
  forward_tacotron:
    build: .
    ports:
      - 9999:9999
    volumes:
        - ../assets/data:/root/ForwardTacotron/data
    environment:
      - PASSWORD=secret
    tty: true