version: '2'
services:
  forward_tacotron:
    build: .
    ports:
      - 9999:9999
    volumes:
        - ../../datasets:/root/ForwardTacotron/data
        - ./checkpoints:/root/ForwardTacotron/checkpoints
    tty: true